/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MockTestIndexRouteImport } from './routes/mock-test/index'
import { Route as MockTestSlugRouteImport } from './routes/mock-test/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestIndexRoute = MockTestIndexRouteImport.update({
  id: '/mock-test/',
  path: '/mock-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestSlugRoute = MockTestSlugRouteImport.update({
  id: '/mock-test/$slug',
  path: '/mock-test/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mock-test/$slug': typeof MockTestSlugRoute
  '/mock-test/': typeof MockTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mock-test/$slug': typeof MockTestSlugRoute
  '/mock-test': typeof MockTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mock-test/$slug': typeof MockTestSlugRoute
  '/mock-test/': typeof MockTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mock-test/$slug' | '/mock-test/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mock-test/$slug' | '/mock-test'
  id: '__root__' | '/' | '/mock-test/$slug' | '/mock-test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MockTestSlugRoute: typeof MockTestSlugRoute
  MockTestIndexRoute: typeof MockTestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test/': {
      id: '/mock-test/'
      path: '/mock-test'
      fullPath: '/mock-test/'
      preLoaderRoute: typeof MockTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test/$slug': {
      id: '/mock-test/$slug'
      path: '/mock-test/$slug'
      fullPath: '/mock-test/$slug'
      preLoaderRoute: typeof MockTestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MockTestSlugRoute: MockTestSlugRoute,
  MockTestIndexRoute: MockTestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
